spring.application.name=PostBoardTest
# H2 ?? ?? (???? ??, ?? ????)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# H2 ??(? ??) ???
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JPA? ???? SQL? ??? ??
spring.jpa.show-sql=true
# ??? ?? ?? ?? (Entity ??)
spring.jpa.hibernate.ddl-auto=update
jwt.secret:#*$&%^laksdjfhgqpw1092834756oeirutyzmnxcbv!)@(#*
# ?? ?? ?? (1?? = 1000 * 60 * 60 ms)
jwt.expiration:3600000
